### PR TITLE
Refactor(pangram): remove unnecessary string operations in `example.nim`

### PR DESCRIPTION
**Pull request by ynfle**
This change results in a speed up of about 3-4x on my machine

Review on the commit message is greatly appreciated

### CODE REVIEW

**Comment by ynfle** [comment]
Is this something that should be done as `example.nim` isn't necessarily the "best" solution?

**Comment by ErikSchierboom** [comment]
> Is this something that should be done as example.nim isn't necessarily the "best" solution?

Different tracks treat this differently. I usually try to come up with the "best" solution when doing these example files, but that's just personal preference. Exercism doesn't really care how good the code is, as long as it passes the tests.

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ynfle** [comment]
@ee7 what do you think?

**Comment by ee7** [comment]
I'll merge soon, since this is clearly an improvement.

Improving the example solutions in this repo hasn't been a high priority for me; the examples aren't user facing, so there is a potential argument that it's more "valuable" to work on nearly anything else.

However, not everything is about "value for the end user". And updating the examples does have potential to help Nim mentors.

I do have an `example.nim` that I found mostly reasonable for every exercise (written long ago). So if we're interested in working on the examples, would it be OK if I ask that you don't work on improving the examples until I've created an initial wave of PRs? Then I'd love for you (and maybe Erik too? :)) to tear them apart. After all, working on exercise solutions is how we all us got started with Exercism, so it'd be nice to go back to the roots a bit.

**Comment by ee7** [comment]
Sorry for the delay - thanks for the PR.

Looks like a further 10x speedup is possible for this exercise, using the test suite as an input.

**Comment by ynfle** [comment]
> I do have an `example.nim` that I found mostly reasonable for every exercise (written long ago). So if we're interested in working on the examples, would it be OK if I ask that you don't work on improving the examples until I've created an initial wave of PRs?

Can you be more specific about what you mean/intend?

**Pull request merged**
