### PR TITLE
Implement exercise: clock

### PR DESCRIPTION
**Pull request by ee7**
### Problem specifications
[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/clock/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/clock/canonical-data.json)

### Comments
Many tracks (e.g. Python, Go, Rust, F#, C#, Ruby) use `clock` as a `core` exercise. There might be better choices for the Nim track.

### CODE REVIEW

**Comment by ee7** [comment]
Force-pushes:
1. [Rename `initClock` to `create`](https://github.com/exercism/nim/compare/e24066d7111ab997357f66a657ffaddbdfa56b4e..c58c4402649c00790df7f0f7296228865d59d821)
2. [Implement `subtract` function](https://github.com/exercism/nim/compare/c58c4402649c00790df7f0f7296228865d59d821..3937f52bd12233fb3c872c6b1a0b5b90e1304c5c)
3. [Replace `while` with `if`](https://github.com/exercism/nim/compare/3937f52bd12233fb3c872c6b1a0b5b90e1304c5c..681899a250ca888e2e10f24619977bb0a1e1a7ed)
4. [Rebase on `master` with no other changes](https://github.com/exercism/nim/compare/681899a250ca888e2e10f24619977bb0a1e1a7ed..fce619278a5d65fe703ab6a6688a894f09721d6a)

Some tracks like [Rust](https://github.com/exercism/rust/blob/master/exercises/clock/tests/clock.rs#L190) use an `add` function with negative minutes instead of a `subtract` function, but still declare compliance with the latest version of the `canonical-data`.

I decided to just follow upstream.

### Travis
Travis still seems to behave strangely with draft PRs. Sometimes it doesn't build at all (there was no build for `sublist`). Other times it builds too much (it just ran 3 times on the same commit for `clock`).

**Comment by amscotti** [comment]
On your comment, with all the new exercise coming in we will be reorganizing the layout of the track. I been waiting for all the draft PRs to be closed for we have all the exercised added to the project before reorganizing, but yes this will be happening.

**Comment by ee7** [comment]
@amscotti Apologies for the delay. I should be able to make progress again now.

> Great work!

Thanks.

**Comment by amscotti** [comment]
@ee7 no need to apologize, you been doing great work and I appreciate all the new exercises you are adding! 👍

**Pull request merged**
