### PR TITLE
exercises(list-ops): implement

### PR DESCRIPTION
**Pull request by Norbiox**
I have added missing exercise "list-ops" according to my proposition in [this thread on forum](https://forum.exercism.org/t/add-practice-exercise-list-ops-to-the-nim-track/9426). 
Unfortunately I have failed to provide 2 tests and solutions for them - it's about handling nested lists in `concatenate` and `reverse`. I've tried generics but found no working solutions. I also looked at implementations of this task in other statically typed languages, but they've been missing those cases too.  As I'm pretty new to statically typed languages I need to deepen my understanding of that topic.

### CODE REVIEW

**Review by siebenschlaefer — COMMENTED** [review]
# tests.toml

tests.toml should describe which tests from the canonical-data.json are implemented in the language-specific translation.
[Lines 52-62](https://github.com/exercism/nim/pull/557/files#diff-cba2bd849b399544883769c1ca57d3a6cb539c0b50654ac6372787680200e7d4R52-R62) and [76-86](https://github.com/exercism/nim/pull/557/files#diff-cba2bd849b399544883769c1ca57d3a6cb539c0b50654ac6372787680200e7d4R76-R86) claim that three tests are *not* implemented but actually they are ([lines 56-66](https://github.com/exercism/nim/pull/557/files#diff-5cc036b49e250ddb36af2625fd3b046e8efe2343fe43d657a79deb27aca5364dR56-R66) and [82-92](https://github.com/exercism/nim/pull/557/files#diff-5cc036b49e250ddb36af2625fd3b046e8efe2343fe43d657a79deb27aca5364dR56-R66)).

# test_list_ops.nim

The suite for `foldl` implements six tests (lines 55-78).
But the three latter tests are meant as replacements for the three former ones, specified via "reimplements"
(e.g. https://github.com/exercism/problem-specifications/blob/main/exercises/list-ops/canonical-data.json#L206).)
I'd suggest deleting the three tests in lines 56-66.

It's similar for the suite for `foldr` (lines 81-104), the latter three tests are meant as replacements for the former three tests.

The tests "empty list" in the suites for `foldl` (lines 68-70) and `foldr` (lines 94-96) define a `function` that *adds* its two parameters.
Why not stay true to the [canonical-data.json](https://github.com/exercism/problem-specifications/blob/main/exercises/list-ops/canonical-data.json#L216) and *multiply* the parameters?

The tests "direction dependent function applied to non-empty list" for `foldl` (lines 76-78 ) and `foldr` (lines 102-104) define a `function` that uses a subtraction.
The [canonical-data.json](https://github.com/exercism/problem-specifications/blob/main/exercises/list-ops/canonical-data.json#L251) uses a division and explicitly mentions in a [comment](https://github.com/exercism/problem-specifications/blob/main/exercises/list-ops/canonical-data.json#L241-L245) that "if integer division is expected / required" the test data from the old version should be used.

The tests uses parameter names `acc` and `el` for the `function` that make it clear which argument is the accumulator.
see https://github.com/exercism/problem-specifications/blob/main/exercises/list-ops/canonical-data.json#L162-L165
They even reimplemented the three tests for `foldl` so this seems to be important.

The tests uses parameter names `acc` and `el` for the `function` that make it clear which argument is the accumulator.
see https://github.com/exercism/problem-specifications/blob/main/exercises/list-ops/canonical-data.json#L260-L263
They even reimplemented the three tests for `foldl` so this seems to be important.
I'd suggest using similarly expressive names instead of `x` and `y`.

---

# list_ops.nim (stub)

In the initial stub the second parameter for `foldl` and `foldr` is defined as `function: proc(x, y: int): int`.
`x` and `y` are pretty generic names. IIRC that has confused some students and caused debates.
It was decided to rename these parameters to `acc` and `el` so that it would be obvious which one is the accumulator.
That was the reason why the three original tests for `foldl` and `foldr` were replaced.
I'd suggest using similarly expressive names instead of `x` and `y`, to stay close to the canonical-data.json and to avoid confusion.

The [canonical-data.json] contains a comment regarding the order of the arguments for the function that gets passed to `foldl` and `foldr`.
It basically says that there are different conventions, we should use the one common to the programming language.
Nim has the template `foldl` and `foldr` in the `sequtils` module.
[foldl](https://nim-lang.org/docs/sequtils.html#foldl.t,,,) takes an expression where `a` is the accumulator and `b` the element,
whereas [foldr](https://nim-lang.org/docs/sequtils.html#foldr.t,untyped,untyped) takes an expression where `a` is the element and `b` is the accumulator.

I'd suggest changing the `function` in the "direction dependent" tests for `foldr` so that our `foldr` behaves similarly to `sequtils.foldr`:
```nim
do_assert sequtils.foldl(@[5, 7], a - b, 0) == -12
do_assert sequtils.foldl(@[1, 20, 300], a - b, 0) == -321
do_assert foldl(@[5, 7], func(acc, el: int): int = acc - el, 0) == -12
do_assert foldl(@[1, 20, 300], func(acc, el: int): int = acc - el, 0) == -321

do_assert sequtils.foldr(@[5, 7, 0], a - b) == -2
do_assert sequtils.foldr(@[1, 20, 300, 0], a - b) == 281
do_assert foldr(@[5, 7], func(el, acc: int): int = el - acc, 0) == -2
do_assert foldr(@[1, 20, 300], func(el, acc: int): int = el - acc, 0) == 281
```

---

# example.nim

The example solution uses `openArray` almost everywhere for the parameters, whereas the solution stub uses `seq`.
Did you do that on purpose? How about `openArray` in the solution stub?

**Comment by Norbiox** [comment]
I should've read the `canonical-data.json` first I see. Somehow I missed it in introduction video.

To `example.nim`:  I've used `seq` everywhere, but it was refactored to the point that It's not my PR anymore.

**Comment by siebenschlaefer** [comment]
Oh, I'm sorry to hear that.

**Comment by Norbiox** [comment]
Me too

**Pull request closed without merging**
