### PR TITLE
Add default introductory code example

### PR DESCRIPTION
**Pull request by kytrinyx**
Instead of having logic for a fallback in the backend, we're choosing a
default for the snippet file.

For tracks that have core exercises, we pick the first core exercise.
For tracks without these, we pick the first exercise listed in the config.

See https://github.com/exercism/meta/issues/89

### CODE REVIEW

**Comment by dom96** [comment]
Nice! Thank you for still maintaining the Nim exercises :)

Small nit: ``helloworld`` -> ``helloWorld``.

**Comment by kytrinyx** [comment]
Ah, sweet. I'll make that change, thanks!

**Comment by kytrinyx** [comment]
Fixed! Thanks @dom96

**Comment by kytrinyx** [comment]
I was, though if you had been busy I probably would have just merged it eventually :-)

Thank you ✨

**Comment by kytrinyx** [comment]
Also @dom96 -- would you be interested in having commit on this repo? It's not super high volume, and you wouldn't be expected to do anything more than you are already doing. I really appreciate your input on these things.

**Pull request merged**
