### PR TITLE
exercises(robot-simulator): implement

### PR DESCRIPTION
**Pull request by ilmanzo**
Reference to issue #555
Implement the missing robot-simulator exercise in Nim

### CODE REVIEW

**Comment by ynfle** [comment]
@ee7 @ilmanzo what is the state of this PR?

**Comment by ilmanzo** [comment]
> @ee7 @ilmanzo what is the state of this PR?

@ee7 did a lot of refactoring so now it seems pretty good at least for me :) Waiting for a final review I guess

**Review by ynfle — APPROVED** [review]
Overall looks great.

My only comment would be that perhaps the instructions could be a seq of an enum to ensure type safety at the caller level. Non blocking, though

**Comment by ynfle** [comment]
I'm going to merge this in a couple of days if @ee7 is available for a review

**Pull request closed without merging**
